# Generated by Django 6.1 on 2026-08-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hairstylist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstylist',
            name='category',
            field=models.CharField(choices=[('hairstylist', 'Hairstylist'), ('barber', 'Barber'), ('nail_tech', 'Nail Tech')], default='hairstylist', help_text='Lets clients filter between hairstylists, barbers, and nail techs when browsing.', max_length=20),
        ),
    ]
