# Generated by Django 6.1 on 2026-08-18 19:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_hairstylist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylist',
            name='address',
            field=models.CharField(blank=True, help_text='Salon/shop address shown on the booking card', max_length=300),
        ),
        migrations.AddField(
            model_name='hairstylist',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Profile photo uploaded via admin. Stored on Cloudinary.', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='hairstylist',
            name='photo_url',
            field=models.URLField(blank=True, help_text='External photo URL (fallback if no uploaded photo)'),
        ),
    ]
