# Generated by Django 6.1 on 2026-08-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_client_email_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstylist',
            name='category',
            field=models.CharField(choices=[('hairstylist', 'Hairstylist'), ('barber', 'Barber')], default='hairstylist', help_text='Lets clients filter between hairstylists and barbers when browsing.', max_length=20),
        ),
    ]
